version: "3.9"

services:

  db:
    container_name: cash-database
    image: postgres:15
    environment:
      - POSTGRES_DB=cash
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=strongpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - main
    restart: always

  django:
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    container_name: cash-back
    command: ./docker/web_entrypoint.sh
    environment:
      - DATABASE_URL=psql://admin:strongpassword@db:5432/cash
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - main
    restart: always

volumes:
    postgres-data:

networks:
  main:
