name: CI

on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds and tests the Django app using Docker
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Builds Docker containers
      - name: ‌‌Build Docker containers
        run: docker compose up -d --build

      # Waits for a few seconds to let the app start
      - name: Wait for app to start
        run: sleep 10

      # Runs tests using the Django test command
      - name: Run tests
        run: docker exec link-shortener pytest
